namespace: cazier
name: zfs
version: 1.0.0

authors:
- Brendan Cazier <520246+cazier@users.noreply.github.com>

readme: README.md
description: A minimal (and probably slightly dangerous) collection to interact with, create, configure, destroy, etc. ZFS zpools
license_file: 'LICENSE'

repository: https://github.com/cazier/ansible-zpool
documentation: https://github.com/cazier/ansible-zpool
homepage: https://github.com/cazier/ansible-zpool
issues: http://example.com/issue/tracker

tags:
  - zpool
  - dangerous

build_ignore: []
