namespace: cazier
name: utils
version: 1.0.0

authors:
- Brendan Cazier <520246+cazier@users.noreply.github.com>

readme: README.md
description: Helper module with some added facts because I don't really wanna use facts.d
license_file: 'LICENSE'

repository: https://github.com/cazier/ansible-zpool
documentation: https://github.com/cazier/ansible-zpool
homepage: https://github.com/cazier/ansible-zpool
issues: http://example.com/issue/tracker

tags:
  - brew
  - homebrew
  - linuxbrew
  - ohmyzsh

build_ignore: []
