name: Linters and Formatters

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - review_requested

defaults:
  run:
    working-directory: cazier

jobs:
  type-hints:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only static
      - run: poetry run mypy .

  linters:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only static
      - run: poetry run pylint .
      - run: poetry run darglint .

  formatters:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only static
      - run: poetry run isort . --check
      - run: poetry run black . --check
