name: Test Python Files
on:
  push:
    branches:
      - main

  pull_requests:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only testing
      - run: poetry run ward test -p tests
