name: Zpool testing
on:
  push:
    branches:
      - main
      - ansible-start

jobs:
  zpools:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          sudo apt update
          sudo apt install -y zfsutils-linux
          /sbin/modprobe zfs
      - run: |
          python -m pip install poetry
          poetry install --only testing
      - run: |
          poetry run ward test -p tests --tags ansible
